name:  simant
title:   SimAnt - The Electronic Ant Colony (DOS)
version: "1.0"
summary:  Ants are so much like human beings as to be an embarrassment
description: |
  Ants are simple, even stupid individuals. But an ant colony, through the interaction of a great number of ants, displays an amazing skill at survival, and a noticeable level of intelligence.In SimAnt, you are the intelligence of an ant colony. The individual ants are like the individual brain cells of your being. You will hop into and out of individual ants, using them as tools. many of your ants will dies, including at times the one you are inhabiting. but death of individual ants will not greatly affect you as a colony. in fact, one of your ants dying will hurt you about as much as a human trimming a fingernail.

grade: stable
icon: simant_icon.png

base: core18
confinement: strict

architectures:
  - build-on: amd64
  - build-on: i386

environment:
  WINEDLLOVERRIDES: "$WINEDLLOVERRIDES;mscoree,mshtml="    # Prevent pop-ups about Wine Mono and Wine Gecko
  SOMMELIER_STRICT: "1"                                    # Make Sommelier exit when unset variable is used. (useful to find bugs in sommelier)

apps:
  simant:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier run-exe
    environment:
      RUN_EXE: "SIMANT.EXE"
      #INSTALL_EXE: "$SNAP/Blockout25_setup.exe"
      #INSTALL_FLAGS: "/S"
    plugs:
      - home
      - network
      - network-bind
      - removable-media
      - cups
  # The wine command can be used to run applications inside the wine
  # environment that this snap uses.
  #
  # For example, users can configure the wine environment of this snap
  # by running `myapp.wine winecfg`.
  wine:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier
    plugs:
      - home
      - network
      - network-bind
      - removable-media
      - cups
 # The winetricks command can be used to run winetricks inside the wine
  # environment that this snap uses.
  winetricks:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier winetricks
    plugs:
      - network

parts:
  installer:
    plugin: dump
    source: ./

  # The sommelier script helps you snap Windows applications using Wine. It 
  # initializes and configures Wine and installs the Windows application.
  sommelier:
    plugin: make
    source: https://github.com/snapcrafters/sommelier-core.git

# These plugs are used to connect the snap to the wine runtime.
plugs:
  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  wine-5-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-5-stable

